export const DISTRICTS = [
  'ALBURQUERQUE', 'ALICIA', 'ANDA', 'ANTEQUERA', 'BACLAYON', 'BALILIHAN', 'BATUAN', 'BIEN UNIDO', 'BILAR', 'BUENAVISTA', 'CALAPE', 'CANDIJAY', 'CARMEN 1', 'CARMEN 2', 'CATIGBIAN', 'CLARIN', 'CORELLA', 'CORTES', 'DAGOHOY', 'DANAO', 'DAUIS', 'DIMIAO', 'DUERO', 'GARCIA HERNANDEZ', 'GETAFE', 'GUINDULMAN', 'INABANGA NORTH', 'INABANGA SOUTH', 'JAGNA', 'LINTAON', 'LILA', 'LOAY', 'LOBOC', 'LOON NORTH', 'LOON SOUTH', 'MABINI', 'MARIBOJOC', 'PANGLAO', 'PILAR', 'PRES. CARLOS P. GARCIA', 'SAGBAYAN', 'SAN ISIDRO', 'SAN MIGUEL', 'SEVILLA', 'SIERRA BULLONES', 'SIKATUNA', 'TALIBON 1', 'TALIBON 2', 'TRINIDAD', 'TUBIGON EAST', 'TUBIGON WEST', 'UBAY 1', 'UBAY 2', 'UBAY 3', 'VALENCIA'
];

export const GRADES = [
  'Kindergarten', 'Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Grade 5', 'Grade 6', 'Grade 7', 'Grade 8', 'Grade 9', 'Grade 10', 'Grade 11', 'Grade 12'
];

export const REASONS = [
  'Health Issues', 'Conflict Affected', 'Work Commitments', 'Children in Need of Care and Protection', 'Children in Conflict with the Law', 'Child Deprived with Liberty', 'Remote Areas', 'Others'
];

export const ACADEMIC_STATUSES = [
  '(90-100) Outstanding',
  '(85-89) Very Satisfactory',
  '(80-84) Satisfactory',
  '(75-79) Fairly Satisfactory',
  '(Below 75) Did not meet expectations'
];

export const ASSESSMENTS = [
  'Pending',
  'Continue ADM',
  'Back to Regular Class'
];

export const DISTRICTS_BY_CD: Record<string, string[]> = {
  'CD1': ['ALBURQUERQUE', 'ANTEQUERA', 'BACLAYON', 'BALILIHAN', 'CALAPE', 'CATIGBIAN', 'CORELLA', 'CORTES', 'DAUIS', 'LOON NORTH', 'LOON SOUTH', 'MARIBOJOC', 'PANGLAO', 'SIKATUNA', 'TUBIGON-EAST', 'TUBIGON-WEST'],
  'CD2': ['BIEN UNIDO', 'BUENAVISTA I', 'BUENAVISTA II', 'CLARIN', 'DAGOHOY', 'DANAO', 'GETAFE I', 'GETAFE II', 'INABANGA NORTH', 'INABANGA SOUTH', 'PRES CPG', 'SAGBAYAN', 'SAN ISIDRO', 'SAN MIGUEL', 'TALIBON I', 'TALIBON II', 'TRINIDAD I', 'TRINIDAD II', 'UBAY I', 'UBAY II', 'UBAY III'],
  'CD3': ['ALICIA', 'ANDA', 'BATUAN', 'BILAR', 'CANDIJAY', 'CARMEN I', 'CARMEN II', 'CARMEN III', 'DIMIAO', 'DUERO', 'GARCIA HERNANDEZ', 'GUINDULMAN', 'JAGNA', 'LILA', 'LOAY', 'LOBOC', 'MABINI', 'PILAR', 'SEVILLA', 'SIERRA BULLONES', 'VALENCIA']
};

export const SCHOOLS_BY_DISTRICT: Record<string, string[]> = {
  'ALBURQUERQUE': ['Alburquerque CES', 'Bahi PS', 'Canlimpong PS', 'Cantiguib ES', 'Dangay ES', 'Tagbuane ES', 'Toril ES', 'Erico B. Aumentado HS', 'San Roque NHS'],
  'ALICIA': ['Alicia CES', 'Alicia CES-Annex', 'Cabatang ES', 'Cambaol ES', 'Cagongcagong ES', 'Cayacay ES', 'Del Monte ES', 'Katipunan ES', 'Katipunan ES-Annex', 'La Hacienda ES', 'Mahayag ES', 'Napo ES', 'Pagahat ES', 'Progreso ES', 'Putlongcam ES', 'Sudlon ES', 'Untaga ES', 'Alicia TVHS', 'Cayacay HS', 'Katipunan HS', 'La Hacienda NHS'],
  'ANDA': ['Anda CES', 'Abihid ES', 'Almaria ES', 'Bacong ES', 'Badiang ES', 'Buenasuerte ES', 'Candabong ES', 'Casical ES', 'Ipo ES', 'Mahayahay ES', 'Linawan ES', 'Londag ES', 'Porcenas ES', 'Suba ES', 'Talisay ES', 'Tanod ES', 'Virgen', 'Anda HS', 'Badiang NHS', 'Candabong NHS'],
  'ANTEQUERA': ['Angilan ES', 'Antequera CES', 'Bantolinao ES', 'Bicahan ES', 'Bitaugan ES', 'Bungahan ES', 'Canlaas ES', 'Can-omay ES', 'Cansibuan ES', 'Danao ES', 'Obujan-Tagubaas ES', 'Quinapon-an ES', 'Sto. Rosario ES', 'Tabuan ES', 'Tupas ES', 'Viga ES', 'Villa Aurora ES', 'Bantolinao NHS', 'Canlaas HS', 'Tupas HS', 'Villa Aurora HS'],
  'BACLAYON': ['Baclayon CES', 'Cambanac PS', 'Dasitam ES', 'Guiwanon ES', 'Laya ES', 'Libertad ES', 'MOMES', 'Montana ES', 'Pamilacan ES', 'Payahan ES', 'Tanday ES', 'Tunga ES', 'Baclayon NHS', 'Pamilacan HS'],
  'BALILIHAN': ['Balilihan CES', 'Baucan ES', 'Boctol ES', 'Boyog ES', 'Cabad-Candasig ES', 'Cantalid PS', 'Cantomimbo PS', 'Cogon-Tagustusan ES', 'Datag ES', 'Dorol ES', 'Haguilanan Grande ES', 'Hanopol ES', 'Magsija-Maslog ES', 'Sagasa ES', 'Sal-ing ES', 'San Isidro PS', 'San Roque IS', 'Cong. Pablo Malasarte NHS', 'Hanopol NHS', 'San Roque NHS'],
  'BATUAN': ['Behind the Clouds PS', 'BCES Main', 'BCES Annex', 'Bonifacio ES', 'Cabacnitan ES', 'Cantigdas ES', 'Cambacay ES', 'Garcia ES', 'Janlud ES', 'Lungsod-daan ES', 'Quezon ES', 'Quirino PS', 'Rizal ES', 'Rosariohan ES', 'Sta. Cruz ES', 'Batuan NHS', 'Rizal HS', 'Quezon HS'],
  'BIEN UNIDO': ['Bien Unido CES', 'Bilangbilangan Daku ES', 'Bilangbilangan East ES', 'Hingotanan ES', 'Liberty ES', 'Nueva Esperanza ES', 'Pinamgo ES', 'Mandawa ES', 'Maomawan IS', 'Nueva Estrella ES', 'Sagasa ES', 'Puerto San Pedro ES', 'Tuboran ES', 'Hingotanan NHS', 'Nueva Esperanza NHS', 'PCPGTVSFA', 'Ponciano L. Padin NHS', 'Maomawan IS', 'Modesto G. Autida HS'],
  'BILAR': ['Bilar CES', 'Bonifacio ES', 'Bugang ES', 'Cabacnitan ES', 'Cambigsi ES', 'Campagao ES', 'Cansumbol', 'Dagohoy ES', 'Owac ES', 'Quezon ES', 'Riverside ES', 'Rizal ES', 'Roxas ES', 'Subayon ES', 'Villa Aurora ES', 'Villa Suerte ES', 'Yanaya ES', 'Zamora ES', 'Bilar NHS', 'Campagao HS'],
  'BUENAVISTA I': ['Asinan ES', 'Bago ES', 'Bantuan ES', 'Bonotbonot ES', 'Buenavista I CES', 'Cabul-an ES', 'Cambus-oc ES', 'Cantores ES', 'Catigbian ES', 'Lubang ES', 'Lusong ES', 'Nueva Granada ES', 'Overland ES', 'P. Tirol ES', 'Rufo Hill ES', 'Cabul-an NHS', 'Buenavista Municipal HS', 'Lubang NHS'],
  'BUENAVISTA II': ['Buenavista II CES', 'Bato ES', 'Cantomogcad ES', 'Cambuhat ES', 'Cantuba ES', 'Nueva Montaña ES', 'Cawag ES', 'Dait Norte ES', 'Baluarte ES', 'Lapacan Norte PS', 'Buga-ong ES', 'Panghagban ES', 'Panghagban HS', 'Cangawa NHS'],
  'CALAPE': ['Banlasan ES', 'Bentig-Calunasan ES', 'Bonbon-Catmonan ES', 'Cabudburan ES', 'Cabayugan ES', 'Calape CES', 'Camias ES', 'Canguha ES', 'Kinabag-an ES', 'Labuon ES', 'Mandaug ES', 'Mandaug Gamay ES', 'Mantatao ES', 'Pangangan ES', 'Ulbujan ES', 'Tultugan ES', 'Sampoangon ES', 'San Isidro ES', 'Tinibgan ES', 'Fermin Tayabas NHS', 'Calape NHS', 'Pangangan NHS', 'MARTNSF'],
  'CANDIJAY': ['Abihilan ES', 'Anoling ES', 'Boyoan ES', 'Cambane ES', 'Canawa ES', 'Candijay CES', 'Can-olin ES', 'Cogtong ES', 'Mahangin ES', 'La Union ES', 'Luan ES', 'Lungsodaan ES', 'Pagahat ES', 'Panadtaran ES', 'Panas ES', 'Pangpang ES', 'San Isidro ES', 'Tambongan ES', 'Tawid ES', 'Tubod ES', 'Tugas ES', 'Anoling NHS', 'Candijay MHS', 'Candijay NHS', 'Cogtong NHS', 'La Union NHS', 'Tambongan NHS'],
  'CARMEN I': ['Alegria ES', 'Calatrava ES', 'Carmen 1 CES', 'Lapu-Lapu ES', 'La Victoria ES', 'Matin-ao ES', 'Nueva Fuerza ES', 'Tagaonan ES', 'Tamboan ES', 'Villaflor ES', 'Villarcayo ES', 'Isabel SJ Gujol MHS', 'Policronio S. Dano Sr. HS', 'Ponciano F. Ramasola HS', 'Valeriano A. Ganas HS'],
  'CARMEN II': ['Bohog ES', 'Buenos Aires ES', 'Carmen 2 CES', 'Guadalupe ES', 'La Libertad ES', 'La Paz ES', 'La Salvacion ES', 'Montehermoso ES', 'Montesunting ES', 'Montevideo ES', 'Nueva Vida Este ES', 'Nueva Vida Norte ES', 'Nueva Vida Sur ES', 'Vallehermoso ES', 'Francisco L. Adlaon HS', 'Vallehermoso HS'],
  'CARMEN III': ['Bicao ES', 'Buenavista ES', 'Can-inas ES', 'Carmen 3 CES', 'El Progreso ES', 'El Salvador ES', 'Montesuerte ES', 'Tuan ES', 'Villafuerte ES', 'Ambassador Pablo R. Suarez NHS', 'Katipunan NHS', 'Pedro S. Budiongan HS'],
  'CATIGBIAN': ['Alegria ES', 'Ambuan ES', 'Baang ES', 'Bagtic ES', 'Bongbong ES', 'Cambailan ES', 'Catigbian CES', 'Catigbian WCES', 'Causwagan ES', 'Hagbuaya ES', 'Haguilanan ES', 'Kang-iras ES', 'Liboron ES', 'Mahayag Norte ES', 'Maitum ES', 'Mantasida ES', 'Rizal PS', 'Sinakayanan ES', 'Triple Union ES', 'Valeriano Segura MES', 'Catigbian NHS', 'Hagbuaya HS', 'Haguilanan HS', 'MNHS'],
  'CLARIN': ['Bacani ES', 'Bogtongbod ES', 'Bonbon ES', 'Bontud ES', 'Buangan ES', 'Buacao ES', 'Cabog ES', 'Caboy ES', 'Cantoyoc PS', 'Clarin CES', 'Danahaw IS-ES', 'Mataub ES', 'Nahawan ES', 'Lajog ES', 'Tontunan ES', 'Tubod PS', 'Villaflor ES', 'Clarin NSF', 'Danahaw NHS', 'Nahawan NHS', 'Tontunan NHS'],
  'CORELLA': ['Anislag ES', 'Corella Central ES', 'Canangcaan ES', 'Canapnapan ES', 'Cancatac ES', 'Sambog ES', 'Tanday ES', 'Canangcaan IS', 'Corella NHS'],
  'CORTES': ['Cortes CES', 'Dela Paz ES', 'Fatima ES', 'Loreto ES', 'Lourdes ES', 'Malayo ES', 'Monserrat ES', 'New Lourdes ES', 'Patrocinio ES', 'Rosario ES', 'San Roque ES', 'Upper Dela Paz ES', 'Dela Paz HS', 'Fatima NHS', 'Loreto HS', 'Lourdes HS'],
  'DAGOHOY': ['San Miguel ES', 'Dagohoy CES', 'Malitbog ES', 'Candelaria ES', 'Mahayag ES', 'Can-oling ES', 'San Vicente ES', 'La Esperanza ES', 'Cagawasan ES', 'Estaca ES', 'Villa Aurora ES', 'Sta. Cruz ES', 'Babag ES', 'Caluasan ES', 'Kagawitan ES', 'Dagohoy NHS', 'San Miguel-Puertos HS'],
  'DANAO': ['Cabatuan ES', 'Cantubod ES', 'Carbon ES', 'Concepcion ES', 'Dagohoy ES', 'Danao CES', 'Danao Gamay ES', 'Hibale ES', 'Magtangtang ES', 'Nahud ES', 'Remedios ES', 'Rowena Heights ES', 'San Carlos ES', 'San Jose ES', 'San Miguel ES', 'Santa Ana ES', 'Santa Fe ES', 'Santo Niño ES', 'Tabok ES', 'Taming ES', 'Villa Anunciado ES', 'Cantubod NHS', 'Danao NHS', 'Francisco Dagohoy MHS', 'Taming NHS'],
  'DAUIS': ['Biking ES', 'Bingag ES', 'Catarman ES', 'Dao ES', 'Dauis CES', 'Mariveles ES', 'Mayacabac ES', 'San Isidro ES', 'Songculan ES', 'Tabalong ES', 'Tinago ES', 'Totolan ES', 'Biking TVHS', 'Dao NHS', 'Dauis NHS', 'Tabalong NHS'],
  'DIMIAO': ['Banban ES', 'Bauhugan ES', 'Cabagakian ES', 'Cadap-agan ES', 'Cambayaon ES', 'Canhayupon ES', 'Canlambong ES', 'Catugasan ES', 'Dimiao CES', 'Guindaguitan ES', 'Lapsaon ES', 'Limokon ES', 'Oac ES', 'Pagsa ES', 'Tangohay ES', 'Canhayupon NHS', 'Dimiao NHS'],
  'DUERO': ['Alejawan PS', 'Angilan ES', 'Anibongan PS', 'Bangwalog ES', 'Buayahan ES', 'Cansuhay ES', 'Danao ES', 'Duay PS', 'Duero CES', 'Guba ES', 'Guinsularan ES', 'Itum PS', 'Langkis PS', 'Lobogon ES', 'Madua Norte PS', 'Madua Sur ES', 'Mambool ES', 'Payao ES', 'San Isidro ES', 'San Pedro ES', 'Taytay ES', 'Bangwalog HS', 'Duero NHS', 'Guinsularan NHS'],
  'GARCIA HERNANDEZ': ['Abijilan ES', 'Antipolo ES', 'Cagwang ES', 'Cambuyo ES', 'Canayaon ES', 'Candulao ES', 'Cayam ES', 'Datag ES', 'Estaca ES', 'Garcia Hernandez Central ES', 'Libertad ES', 'Malinao ES', 'Pasong ES', 'Roxas Park ES', 'Sacaon ES', 'Sampong ES', 'Tabuan ES', 'Togbongon ES', 'Abijilan High School', 'Cambuyo HS', 'Cayam HS', 'Garcia Hernandez High School', 'Tabuan National HS'],
  'GETAFE I': ['Banacon ES', 'Buyog ES', 'Campao ES', 'Corte-Baud ES', 'Getafe 1 CES', 'Jagoliao ES', 'Nasingin ES', 'Pandanon ES', 'Saguise ES', 'Sto. Niño ES', 'Tugas ES', 'Campao Oriental HS', 'Pandanon HS'],
  'GETAFE II': ['Alumar ES', 'Cabasakan ES', 'Cagawasan PS', 'Cangmundo ES', 'Getafe 2 CES', 'Handumon ES', 'Jandayan ES', 'Mahanay ES', 'San Jose ES', 'Salog ES', 'Taytay ES', 'Handumon NHS', 'Tulang NHS'],
  'GUINDULMAN': ['Basdio ES', 'Bato ES', 'Bayong', 'Biabas ES', 'Bulawan ES', 'Cabantian ES', 'Cabugan ES', 'Canhaway ES', 'Casbu ES', 'Catungawan ES', 'Guinacot ES', 'Guindulman Central ES', 'Guio-ang ES', 'Lombog ES', 'Mayuga ES', 'Pansul ES', 'Tabunoc ES', 'Tambis ES', 'Trinidad ES', 'Catungawan NHS', 'Guinacot NHS', 'Mayuga NHS', 'GTVHS'],
  'INABANGA NORTH': ['Anonang ES', 'Baguhan ES', 'Baogo ES', 'Bugang PS', 'Cambitoon ES', 'Causlan PS', 'Cuaming ES', 'Dait Sur ES', 'Datag ES', 'Hambongan ES', 'Incis-ES', 'Lawis ES', 'Liloan Norte ES', 'Liloan Sur ES', 'Ma. Rosario PS', 'Nabuad ES', 'Napo PS', 'Ondol ES', 'San Isidro ES', 'San Jose ES', 'Sto. Niño PS', 'Sua PS', 'Cuaming HS', 'Inabanga HS', 'Inabanga North CIS-Secondary', 'San Jose NHS'],
  'INABANGA SOUTH': ['Badiang ES', 'Bahan PS', 'Banahao ES', 'Cagawasan ES', 'Cainsican ES', 'Canlinte PS', 'Cawayan ES', 'Dagnawan ES', 'Dagohoy ES', 'Inabanga South CES', 'Lomboy PS', 'Lonoy PS', 'Lutao ES', 'Luyo PS', 'Mabuhay PS', 'Sto. Rosario ES', 'U-og Ubujan ES', 'Dagnawan Inabanga HS', 'Southern Inabanga HS'],
  'JAGNA': ['Balili ES', 'Boctol ES', 'Bunga Ilaya ES', 'Bunga Mar ES', 'Buyog ES', 'Cabungaan ES', 'Calabacita ES', 'Cambugason ES', 'Canjulao ES', 'Can-ipol ES', 'Cantagay ES', 'Cantuyoc ES', 'Canuba ES', 'Jagna CES', 'Kinagbaan ES', 'Larapan ES', 'Lonoy ES', 'Malbog ES', 'Mayana ES', 'Naatang ES', 'Odiong ES', 'TMIS-Elem', 'Calabacita HS', 'Faraon NHS', 'Jagna HS', 'Lonoy Heroes MHS', 'TMIS-Sec'],
  'LILA': ['Bonkokan ES', 'Calvario ES', 'Cogon ES', 'Jambawan ES', 'Lila CES', 'Macalingan ES', 'Malinao ES', 'Nagsulay ES', 'Tiguis ES', 'Lila NHS'],
  'LOAY': ['Botoc ES', 'Candontol PS', 'CHAMES', 'Concepcion ES', 'Las Salinas ES', 'Sagnap ES', 'SPPJACMS', 'Tambangan ES', 'Tangcasan Norte ES', 'Tayong ES', 'Tocdog ES', 'Villalimpia ES', 'Hinawanan NHS', 'Loay NHS'],
  'LOBOC': ['Agape ES', 'Antonio Felipa ES', 'Bagumbayan ES', 'Bartolome Doria ES', 'Buenavista ES', 'Bugho ES', 'Calunasan Sur ES', 'Candabong ES', 'Gon-ob PS', 'Gotozon ES', 'Quinoguitan ES', 'Loboc Central ES', 'Tigbao ES', 'Tambis ES', 'Triple Union ES', 'Camaya-an NHS', 'Loboc NHS', 'OY NHS'],
  'LOON NORTH': ['Bagacay ES', 'Biasong ES', 'Cabacungan ES', 'Cabilao ES', 'Calayugan ES', 'Cambaquiz ES', 'Canhangdon ES', 'Canigaan-Ubojan ES', 'Cantam-is ES', 'Cantaongon ES', 'Cantomucad ES', 'Genomoan PS', 'Lawis ES', 'Loon North Central ES', 'Mocpoc ES', 'Nueva Vida ES', 'Pondol ES', 'Sondol ES', 'Cabilao NHS', 'GJBNHS', 'Loon North HS', 'Lopez-Dano-Simbajon HS', 'Sandingan NHS'],
  'LOON SOUTH': ['Agsoso ES', 'Badbad ES', 'Basac ES', 'Basdacu PS', 'Bugho PS', 'Cabug PS', 'Campatud ES', 'Cogon Norte ES', 'Lintuan ES', 'Loon South Central ES', 'Nagtubo ES', 'Napo ES', 'Pig-ot ES', 'Sto. Nino De La Paz ES', 'Tangnan PS', 'Ticugan ES', 'Tiwi PS', 'Tubodacu ES', 'Tubodio ES', 'Loon East HS', 'Loon South NHS'],
  'MABINI': ['Abaca IS', 'Abad Santos ES', 'Aguipo ES', 'Banlas ES', 'Baybayon ES', 'Bulawan ES', 'Cabidian ES', 'Cawayanan ES', 'Del Mar ES', 'Lungsodaan ES', 'Mabini Central ES', 'Mahayag ES', 'Marcelo ES', 'Minol ES', 'Paraiso ES', 'San Jose ES', 'San Rafael ES', 'San Roque ES', 'Tabunoc ES', 'Tambo ES', 'Valaga ES', 'Concepcion NHS', 'Lungsodaan HS', 'San Jose HS', 'San Roque NHS', 'Tangkigan IS'],
  'MARIBOJOC': ['Agahay ES', 'Aliguay ES', 'Bayacabac ES', 'Bood PS', 'Busao ES', 'Cabawan ES', 'Candavid ES', 'Dipatlong ES', 'Guiwanon PS', 'Jandig ES', 'Lagtangon ES', 'Lincod ES', 'Maribojoc CES', 'Pagnitoan ES', 'Punta Cruz ES', 'San Isidro ES', 'San Roque ES', 'San Vicente ES', 'Santa Cruz ES', 'Tinibgan ES', 'Toril PS', 'Busao NHS', 'Pagnitoan NHS'],
  'PANGLAO': ['Balicasag ES', 'Bil-isan ES', 'Bolod ES', 'Danao ES', 'Doljo ES', 'Libaong ES', 'Looc ES', 'Lourdes ES', 'Panglao Central ES', 'Panglao Central East ES', 'Tangnan ES', 'Tawala ES', 'Felix E. Bompat HS', 'Lourdes NHS'],
  'PILAR': ['Aurora ES', 'Bagacay ES', 'Bagumbayan ES', 'Bayong ES', 'Buenasuerte ES', 'Cagawasan ES', 'Cansungay', 'Del Pilar ES', 'Ilaud ES', 'Inaghuban ES', 'Lumbay ES', 'Pamacsalan ES', 'Pilar CES', 'La Suerte ES', 'Rizal ES', 'San Isidro ES', 'San Carlos ES', 'San Vicente ES', 'Catagdaan IS', 'Estaca IS', 'Lundag IS', 'Pilar TVHS', 'San Isidro TVHS'],
  'PRES. CPG': ['Aguining ES', 'Basiao ES', 'Baud ES', 'Bayog ES', 'Bogo ES', 'Bonbonon ES', 'Butan ES', 'Campamanog ES', 'Canmangao ES', 'Gaus ES', 'Kabangkalan ES', 'Lapinig ES', 'Lipata ES', 'Popoo ES', 'Pres. CPG CES', 'Saguise ES', 'San Jose IS', 'San Vicente ES', 'Sto. Rosario IS', 'Tilmobo ES', 'Tugnao ES', 'Tugas ES', 'Villa Milagrosa ES', 'Aguining NHS', 'Basiao HS', 'Bonbonon HS', 'Campamanog HS', 'JPCHS', 'Mayor Inocencio B. Mendez HS'],
  'SAGBAYAN': ['Calangahan ES', 'Canmaya Centro ES', 'Canmaya Diot ES', 'Canmano ES', 'Kabasacan ES', 'Kagawasan ES', 'Katipunan ES', 'Langtad ES', 'Libertad Norte-Sur ES', 'Mantalongon ES', 'Sagbayan CES', 'Sagbayan Sur ES', 'San Agustin ES', 'San Antonio ES', 'San Isidro ES', 'San Ramon ES', 'San Roque ES', 'San Vicente Norte ES', 'San Vicente Sur ES', 'Sta. Catalina ES', 'Sta. Cruz ES', 'Canmaya Diot HS', 'Clemente Borja NHS', 'Eugenio V. Amores MHS', 'Japer MHS', 'Ubojan IS', 'San Agustin NHS'],
  'SAN ISIDRO': ['Abehilan ES', 'Baryong Daan PS', 'Baunos ES', 'Cabanugan ES', 'Caimbang ES', 'Cambansag ES', 'Candungao ES', 'Cansague Norte ES', 'Cansague Sur ES', 'Causwagan PS', 'Masonoy ES', 'San Isidro CES', 'Cabanugan NHS', 'Cambansag HS', 'Candungao HS', 'San Isidro NHS'],
  'SAN MIGUEL': ['Bayongan ES', 'Bugang ES', 'Cabangahan ES', 'Caluasan ES', 'Camanaga ES', 'Cambangay Norte ES', 'Capayas ES', 'Corazon ES', 'Garcia ES', 'Hagbuyo ES', 'Kagawasan ES', 'Mahayag ES', 'San Isidro ES', 'San Jose ES', 'San Miguel Central ES', 'San Vicente ES', 'Sto. Niño ES', 'Tomoc ES', 'Bugang NHS', 'Mahayag NHS', 'San Miguel Technical Vocational High School', 'Sebastian Jala Memorial HS'],
  'SEVILLA': ['Bayawahan ES', 'Cabancalan PS', 'Calinga-an ES', 'Calinginan Norte ES', 'Calinginan Sur PS', 'Cambagui ES', 'Ewon ES', 'Guinob-an PS', 'Lagtangan ES', 'Licolico ES', 'Lobgob ES', 'Magsaysay ES', 'Sevilla Central ES', 'Bayawahan NHS', 'Cambagui Calinginan Norte NHS', 'Sevilla NHS'],
  'SIERRA BULLONES': ['Abachanan ES', 'Anibongan ES', 'Bugsoc ES', 'Cahayag ES', 'Canlangit ES', 'Cantaub ES', 'Concepcion ES', 'Danicop ES', 'Dusita ES', 'La Union ES', 'Lataban ES', 'Magsaysay ES', 'Matin-ao ES', 'Nan-od ES', 'Salvador ES', 'San Agustin ES', 'San Isidro ES', 'San Jose ES', 'San Juan ES', 'Sbces', 'Sta. Cruz ES', 'Villa Garcia ES', 'Bugsoc HS', 'Dusita HS', 'Nan-od HS', 'Sierra Bullones TVHS'],
  'SIKATUNA': ['Abucay ES', 'Badiang ES', 'Cambuac Norte ES', 'Cambuac Sur ES', 'Sikatuna Central ES', 'Sikatuna NHS'],
  'TALIBON I': ['Balintawak ES', 'Burgos ES', 'Garcia Park ES', 'Magsaysay ES', 'Rizal ES', 'San Agustin ES', 'San Isidro ES', 'San Pedro ES', 'San Roque ES', 'Santo Nino ES', 'Sikatuna ES', 'Talibon Central ES', 'Tanghaligue ES', 'Tunaan Dako ES', 'Zamora ES', 'Talibon NHS', 'San Jose NHS', 'Pres. Carlos P. Garcia Memorial HS'],
  'TALIBON II': ['Alejandro P. Gurrea ES', 'Bansaan ES', 'Bagacay ES', 'Busalian ES', 'Calituban ES', 'Cataban IS-Elementary', 'Domingo R. Yana ES', 'Guindacpan ES', 'Jao ES', 'MAHANAY ES', 'Nocnocan ES', 'PLEBA ES', 'Sag ES', 'San Francisco ES', 'Talibon II Central ES', 'Calituban HS', 'Cataban IS-Secondary', 'Guindacpan HS', 'Mahanay HS', 'Mayor Catalino Y. Casoyla MNHS', 'Ponciana E. Leoligao HS', 'San Jose NHS', 'Zosimo A. Gulle MNHS'],
  'TRINIDAD I': ['Catoogan ES', 'Guinobatan ES', 'La Union ES', 'La Victoria ES', 'Mahagbu ES', 'Panaghiusa ES', 'San Vicente ES', 'Soom IS Elem.', 'Tagum Norte ES', 'Tagum Sur ES', 'Trinidad I CES', 'Trinidad NHS', 'Soom IS Secondary', 'Tagum Sur NHS'],
  'TRINIDAD II': ['Banlasan ES', 'Bongbong ES', 'Diis ES', 'Hinlayagan Ilaya ES', 'Kauswagan ES', 'Kinan-oan ES', 'Loblob ES', 'Mabuhay ES', 'Manuel M. Roxas ES', 'Maonglinis ES', 'San Isidro ES', 'Sto. Tomas ES', 'Trinidad II Central ES', 'Hinlayagan NHS', 'Kauswagan NHS', 'Kinan-oan HS'],
  'TUBIGON EAST': ['Bagonbanua ES', 'Batasan ES', 'Bilangbilangan ES', 'Buenos Aires ES', 'Bunacan ES', 'Cabulijan ES', 'Cawayanan ES', 'Isaac Lopoz ES', 'Libertad ES', 'Mocaboc ES', 'Pangapasan ES', 'Talenceras ES', 'Tan-awan ES', 'Tinangnan ES', 'Tubigon East Central ES', 'Ubay ES', 'Ubojan ES', 'Bagongbanwa HS', 'Cawayanan NHS', 'Tubigon East Central NHS'],
  'TUBIGON WEST': ['Atty. Maximo C. Lasco MES', 'Avelino Chagas MES', 'Banlasan ES', 'Cahayag ES', 'Carmen Mellijor PS', 'Genonocan ES', 'Guiwanon ES', 'Ilijan Sur ES', 'Jose Boja ES', 'Pandan ES', 'Pinayagan Norte ES', 'Pinayagan Sur ES', 'Tubigon West Central ES', 'Villanueva PS', 'Tubigon West Central HS', 'Tubigon West National HS'],
  'UBAY I': ['Achila ES', 'Bood ES', 'Calanggaman ES', 'Camambugan ES', 'Fatima ES', 'Humayhumay ES', 'Katarungan ES', 'Pangpang ES', 'San Isidro ES', 'Sentinela ES', 'Tapal IS', 'Tapon ES', 'Tres Reyes ES', 'Tubog IS', 'Tuboran ES', 'Uces', 'Camambugan NHS', 'Erico B. Aumentado HS', 'Pedro O. Bernales NHS', 'Tapal IS-HS', 'Ubay National Science HS'],
  'UBAY II': ['Benliw ES', 'Cagting ES', 'Cuya ES', 'Guintaboan ES', 'Imelda ES', 'Juagdan ES', 'San Vicente ES', 'Sinandigan ES', 'Tintinan IS', 'Tipolo ES', 'Ubay II Central ES', 'Union ES', 'Biabas Trade HS', 'Cagting HS', 'Tintinan IS', 'Tipolo NHS', 'Union NHS'],
  'UBAY III': ['Bay-ang ES', 'Bongbong ES', 'Buenavista ES', 'Bulilis ES', 'California ES', 'Casate ES', 'Gabi ES', 'Gov. Boyles ES', 'Hambabauran ES', 'Ilihan ES', 'Lomangog ES', 'Luz ES', 'New Los Angeles ES', 'Pag-asa ES', 'San Francisco ES', 'Ubay III Central ES', 'Villa Teresita ES', 'Bulilis HS', 'Don Aguedo Reyes Maboloc NHS', 'Hambabauran HS', 'Ricardo O. Boyles Sr. HS', 'San Pascual National Agri. HS'],
  'VALENCIA': ['Adlawan ES', 'Anas ES', 'Anonang ES', 'Anoyon ES', 'Balingasao-Loctob ES', 'Botong ES', 'Canduao ES', 'Cansibao ES', 'Danao ES', 'Ginopolan ES', 'La Victoria ES', 'Lantang ES', 'Limokon ES', 'Omjon ES', 'Pangi-an ES', 'Simang ES', 'Taculing ES', 'Tausion ES', 'Taytay ES', 'Ticum ES', 'Tipasak ES', 'Valencia Central ES', 'Anas HS', 'Anoyon HS', 'Mayor Pablo O. Lim MHS', 'Valencia TechVoc HS']
};
